version: '3'

services:
  db_tmrtb:
    image: mariadb:10.10.2
    container_name: db_tmrtb
    restart: always
    env_file:
      - .env
    ports:
      - ${MARIADB_PORT}:3306
    expose:
      - 3306
    volumes:
      - ../../trtb-volumes/db/data:/var/lib/mysql
    networks:
      - trtb-dev-net
      
networks:
  trtb-dev-net:
    driver: bridge
    
